# Generated by Django 5.1.2 on 2024-10-28 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0010_tbl_hod'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=30)),
                ('student_email', models.EmailField(max_length=254)),
                ('student_contact', models.CharField(max_length=15)),
                ('student_address', models.TextField()),
                ('student_photo', models.FileField(upload_to='../Assets/Files/Student')),
                ('student_password', models.CharField(max_length=100)),
                ('student_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_course')),
                ('student_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_department')),
            ],
        ),
    ]
