# Generated by Django 5.1.2 on 2024-10-29 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_student',
            name='student_photo',
            field=models.FileField(upload_to='Assets/Files/Student'),
        ),
    ]
