# Generated by Django 5.1.2 on 2024-10-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_tbl_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_activitytype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=30)),
                ('activity_mark', models.CharField(max_length=30)),
            ],
        ),
    ]
