# Generated by Django 5.1.2 on 2024-10-16 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_tbl_activitytype'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_name', models.CharField(max_length=30)),
            ],
        ),
    ]
