# Generated by Django 5.1.2 on 2024-10-16 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_tbl_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_hod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hod_name', models.CharField(max_length=30)),
                ('hod_email', models.CharField(max_length=30)),
                ('hod_contact', models.CharField(max_length=30)),
                ('hod_password', models.CharField(max_length=30)),
                ('hod_department', models.CharField(max_length=30)),
            ],
        ),
    ]
