# Generated by Django 5.1.2 on 2024-10-16 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_tbl_hod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_hod',
            name='hod_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_department'),
        ),
    ]
