# Generated by Django 5.1.2 on 2024-10-16 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_tbl_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_course',
            name='course_department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_department'),
            preserve_default=False,
        ),
    ]
