# Generated by Django 5.1.2 on 2024-10-23 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0008_tbl_course_course_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=30)),
                ('teacher_email', models.CharField(max_length=30)),
                ('teacher_contact', models.CharField(max_length=30)),
                ('teacher_photo', models.CharField(max_length=150)),
                ('teacher_password', models.CharField(max_length=30)),
                ('teacher_hod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_hod')),
            ],
        ),
    ]
