# Generated by Django 5.1.2 on 2024-10-24 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOD', '0002_alter_tbl_teacher_teacher_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_teacher',
            name='teacher_photo',
            field=models.FileField(upload_to='Assets/Files/Teacher'),
        ),
    ]
