# Generated by Django 5.1.2 on 2024-10-24 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HOD', '0003_alter_tbl_teacher_teacher_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_teacher',
        ),
    ]
