# Generated by Django 5.1.2 on 2024-10-23 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0008_tbl_course_course_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('photo', models.ImageField(upload_to='photos/')),
                ('password', models.CharField(max_length=100)),
                ('course_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_course')),
            ],
        ),
    ]
