# Generated by Django 5.1.2 on 2024-10-23 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_user',
            old_name='address',
            new_name='user_address',
        ),
        migrations.RenameField(
            model_name='tbl_user',
            old_name='contact',
            new_name='user_contact',
        ),
        migrations.RenameField(
            model_name='tbl_user',
            old_name='email',
            new_name='user_email',
        ),
        migrations.RenameField(
            model_name='tbl_user',
            old_name='name',
            new_name='user_password',
        ),
        migrations.RenameField(
            model_name='tbl_user',
            old_name='photo',
            new_name='user_photo',
        ),
        migrations.RemoveField(
            model_name='tbl_user',
            name='password',
        ),
    ]
