# Generated by Django 5.1.2 on 2024-10-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0002_rename_address_tbl_user_user_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_user',
            name='user_photo',
            field=models.ImageField(upload_to='../Assets/Files/Student'),
        ),
    ]
