# Generated by Django 5.1.2 on 2024-10-24 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0003_alter_tbl_user_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_user',
            name='user_photo',
            field=models.FileField(upload_to='../Assets/Files/Student'),
        ),
    ]
